ALTER TABLE chat_participants ADD COLUMN IF NOT EXISTS pinned TINYINT(1) NOT NULL DEFAULT 0;
ALTER TABLE chat_participants ADD COLUMN IF NOT EXISTS muted TINYINT(1) NOT NULL DEFAULT 0;
ALTER TABLE chat_participants ADD COLUMN IF NOT EXISTS hidden_at DATETIME NULL;